

# # list comprehension syntax:
# # output_list = [ expression for item in iterable if condition  ]

# n=int(input())
# a=int(input())
# b=int(input())
# c=int(input())
# name_with_a=[(x,y,z) for x in range(a+1) for y in range(b+1) for z in range(c+1) if x+y+z !=n]

# x=range(100)

# print(name_with_a)


########################################################


# mydict={"Name":"mohamed",True:20,"Location":"malk4 da3oa"}
# mydict["Id"]="0903908043"
# print(mydict)

# # 2940606910103038

# for i in mydict.keys():
#     if i in mydict.keys() and


########################################################

count=1

n=int(input())


mydict={"Name":"mohamed",True:20,"Location":"malk4 da3oa"}
if n == 1:
    name=str(input("name"))
    jop=str(input("name"))
    salary=int(input("name"))
    ID=int(input("name"))
    for i in mydict.values():
        if ID != i['ID']:
            mydict[count]={'name':name,'jop':jop,'ID':ID,'salary':salary}
            count+=1
        
elif n==2:
    N=int(input())

    print(mydict[N])
elif n==3:
    B=int(input())
    mydict[B].pop()
########################################################


########################################################


########################################################


########################################################


